# Generated by Django 5.2.2 on 2025-06-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
    ]
