# Generated by Django 5.2.2 on 2025-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_rename_solutions_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.CharField(blank=True),
        ),
    ]
