# Generated by Django 5.0.6 on 2025-06-25 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_discussion_written_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
