# Generated by Django 5.2.2 on 2025-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_alter_problem_code_alter_problem_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='code',
        ),
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.CharField(blank=True),
        ),
    ]
