# Generated by Django 5.2.2 on 2025-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_remove_problem_code_solution_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
