# Generated by Django 5.2.3 on 2025-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_solution_input_data_solution_output_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('cpp', 'C++'), ('java', 'Java'), ('python', 'Python'), ('c', 'C')], max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ManyToManyField(to='oj.topic'),
        ),
    ]
