# Generated by Django 5.2.2 on 2025-06-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_alter_solution_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(),
        ),
    ]
