# Generated by Django 5.0.6 on 2025-06-29 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0008_comment_written_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 29, 8, 55, 55, 400133, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
