# Generated by Django 5.2.3 on 2025-06-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0008_testcase_written_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(),
        ),
    ]
