# Generated by Django 5.0.6 on 2025-07-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0009_comment_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
