# Generated by Django 5.2.3 on 2025-07-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0011_problem_memory_limit_problem_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='contributed_on',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output',
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_file',
            field=models.FileField(default=1, upload_to='testcases/inputs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_file',
            field=models.FileField(default=1, upload_to='testcases/outputs/'),
            preserve_default=False,
        ),
    ]
