# Generated by Django 5.2.3 on 2025-06-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0011_alter_problem_difficulty_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], default='C++'),
            preserve_default=False,
        ),
    ]
