# Generated by Django 5.2.3 on 2025-07-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0012_remove_testcase_contributed_on_remove_testcase_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True),
        ),
    ]
