# Generated by Django 5.2.3 on 2025-06-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0012_solution_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
