# Generated by Django 5.2.3 on 2025-06-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0013_testcase_is_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='is_sample',
        ),
    ]
