# Generated by Django 5.2.3 on 2025-07-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0013_problem_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='ai_feedback',
        ),
    ]
