# Generated by Django 5.2.3 on 2025-07-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0014_remove_solution_ai_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='topic',
            new_name='topics',
        ),
    ]
