# Generated by Django 5.2.3 on 2025-06-20 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0014_remove_testcase_is_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 6, 20, 8, 1, 0, 363801, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 6, 20, 8, 1, 11, 577301, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='contributed_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 6, 20, 8, 1, 17, 518429, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
