# Generated by Django 5.2.3 on 2025-07-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0015_rename_topic_problem_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='passed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
