# Generated by Django 5.2.3 on 2025-06-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0015_problem_date_added_profile_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
