# Generated by Django 5.2.3 on 2025-07-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0016_solution_passed_count_solution_total_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='written_by',
        ),
    ]
