# Generated by Django 5.2.3 on 2025-06-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0016_testcase_is_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='oj.problem'),
        ),
    ]
