# Generated by Django 5.2.3 on 2025-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0017_alter_testcase_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('cpp', 'C++'), ('java', 'Java'), ('python', 'Python')]),
        ),
    ]
