# Generated by Django 5.2.3 on 2025-07-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0018_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='name',
            field=models.CharField(default='Test Contest'),
            preserve_default=False,
        ),
    ]
