# Generated by Django 5.0.6 on 2025-07-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0020_contest_joined_users_alter_contest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
